/**
 * alacnz.server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Case } from './case';


export interface Client { 
    clientId?: number;
    name?: string | null;
    dateOfBirth?: string;
    nationality?: string | null;
    gender?: string | null;
    immigrationStatus?: string | null;
    socialSecurityBenefit?: string | null;
    beneficiariesNationality?: string | null;
    cases?: Array<Case> | null;
}

