/**
 * alacnz.server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Case } from './case';


export interface Session { 
    sessionId?: number;
    sessionDate?: string;
    sessionType?: string | null;
    outcome?: string | null;
    caseId?: number;
    'case'?: Case;
}

