/**
 * alacnz.server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Case } from './case';


export interface SocialWorkTeam { 
    socialWorkTeamId?: number;
    name?: string | null;
    city?: string | null;
    specialty?: string | null;
    cases?: Array<Case> | null;
}

